name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        #python-version: ["3.7", "3.8", "3.9", "3.10"]
        python-version: ["3.x"]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        
    - name: Analysing the code with pylint
      run: |
        #pylint $(find . -name "*.py" | xargs)
        #pylint --disable=C $(find . -name "*.py" | xargs)
        #pylint --const-rgx='[a-z_][a-z0-9_]{2,30}$' $(find . -name "*.py" | xargs)
        pylint --rcfile .github/workflows/.pylintrc --disable=C,R,E,W $(find . -name "*.py" | xargs)
